### ISSUE TITLE
名前空間の宣言方法を変更

### ISSUE THREAD

**Issue by ghost** [makurano/ICB#1]
@makurano 
C# 10 から名前空間の書き方が変わっているのでそれに合わせて変更する。
https://docs.microsoft.com/ja-jp/dotnet/csharp/whats-new/csharp-10#file-scoped-namespace-declaration

参考：
https://github.com/makurano/ICB/blob/main/src/ICB/Data/WeatherForecast.cs

**Comment by makurano** [comment]
対応してプッシュまでしてしまいました

**Comment by orimoto-pic** [comment]
ありがとうございますー

**Comment by ghost** [comment]
ありがとうございますー
